[language-server.assert-lsp]
args = []
command = "testing-language-server"

[[language]]
language-servers = [
    { name = "assert-lsp", only-features = [
        "diagnostics",
    ] },
    "rust-analyzer",
]
name = "rust"

[[language]]
language-servers = [
    { name = "assert-lsp", only-features = [
        "diagnostics",
    ] },
    "typescript-language-server",
]
name = "typescript"

[[language]]
language-servers = [
    { name = "assert-lsp", only-features = [
        "diagnostics",
    ] },
    "phpactor",
]
name = "php"

[[language]]
language-servers = [
    { name = "assert-lsp", only-features = [
        "diagnostics",
    ] },
    "gopls",
]
name = "go"

[[language]]
language-servers = [
    { name = "assert-lsp", only-features = [
        "diagnostics",
    ] },
    "typescript-language-server",
]
name = "javascript"
